### ISSUE TITLE
Make deepsize_derive an optional dependency

### ISSUE THREAD

**Issue by matklad** [Aeledfyr/deepsize#10]
In some cases, it may be preferable to just write a manual impl of `deepsize`, without using derive. For such cases, it would be nice if `derive` support was optional.

Specifically, I am adding deepsize to https://github.com/rust-analyzer/text_unit, and it can work without derive

**Comment by Aeledfyr** [comment]
Would an optional dependancy on the derive that is enabled by a default feature work?  That way it can be disabled, but is still enabled by default.

**Comment by matklad** [comment]
Yeah, optional but default sounds right to me!

**Comment by Aeledfyr** [comment]
This has been fixed in `deepsize` version 0.1.2
