### ISSUE TITLE
Release for deepsize_derive

### ISSUE THREAD

**Issue by adamchalmers** [Aeledfyr/deepsize#17]
Hi! I noticed that the latest deepsize_derive on master is using syn/proc-macro2-quote 1.0 (as of commit ffc79ef6277d3e14a6b5ced49a6f45e825c6c36f), but that commit hasn't been released to crates.io yet! So the current crates.io release is still pulling in old dependencies.

If possible, could you please cut a new release of deepsize_derive? That way, my project can stop compiling the old 0.x dependencies :) Of course, if that's not possible, I can always just point my project at your master branch, instead of using crates.io. But a release would be helpful!

Thanks for your time!

**Comment by Aeledfyr** [comment]
It should be released now; I never realized that I hadn't actually published those changes.

**Comment by adamchalmers** [comment]
Thank you! Could you please also cut a minor release for Deepsize which bumps its dependency on deepsize-derive from 0.1.1 to 0.1.2?
