### ISSUE TITLE
Slotmap support

### ISSUE THREAD

**Issue by dtolnay** [Aeledfyr/deepsize#8]
Moved from https://github.com/dtolnay/request-for-implementation/issues/22#issuecomment-457410613:

> how would I add integration for some of the dynamic storage crates (such as slotmap), without making it a dependency (only using the impl if the crate is already being used)?

**Comment by dtolnay** [comment]
You would need to make slotmap an optional dependency that would be enabled by whichever downstream crates require slotmap support in deepsize. Check out:

- https://doc.rust-lang.org/cargo/reference/manifest.html
- https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by Aeledfyr** [comment]
`slotmap` support has been added in version 0.1.2
